### ISSUE TITLE
[frost-test] DKG and Peg-In (OP_RETURN)

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#65] opened 2023-02-14 22:05 UTC
General idea:

- [x] Run frost dkg using in-process frost library "frost-lib" (no network protocol)
- [x] Peg-in: spend a P2PKH utxo and lock it into P2TR output script using the frost public aggregate key.
- [ ] Confirm Peg-in correctness by submitting to bitcoind regtest node

**Comment by netrome** [comment] 2023-02-17 11:04
@igorsyl it would be very helpful for me reading this if the issue had a well-defined "definition of done" so that I can understand what the goal is.

I understand from the title that this is to write some sort of design doc for a frost/btc integration test, but it would be helpful to know what the test is for and what we want to assert. For example, is the purpose to verify compatibility with the frost signatures and some bitcoin output format?

**Comment by igorsyl** [comment] 2023-02-17 16:20
> I understand from the title that this is to write some sort of design doc for a frost/btc integration test, but it would be helpful to know what the test is for and what we want to assert. For example, is the purpose to verify compatibility with the frost signatures and some bitcoin output format?

Yes, I updated the parent issue with the requirement: https://github.com/Trust-Machines/core-eng/issues/60

> For example, is the purpose to verify compatibility with the frost signatures and some bitcoin output format
Purpose is to learn how to integrate frost with bitcoin using taproot scripts. It should be a single file that we could share with the Degens team who are building the Decentralized Mining Pool with the frost-net library.

**Comment by netrome** [comment] 2023-02-17 16:49
> > I understand from the title that this is to write some sort of design doc for a frost/btc integration test, but it would be helpful to know what the test is for and what we want to assert. For example, is the purpose to verify compatibility with the frost signatures and some bitcoin output format?
> 
> Yes, I updated the parent issue with the requirement: #60
> 
> > For example, is the purpose to verify compatibility with the frost signatures and some bitcoin output format
> > Purpose is to learn how to integrate frost with bitcoin using taproot scripts. It should be a single file that we could share with the Degens team who are building the Decentralized Mining Pool with the frost-net library.
> 
> TBH, a design doc may be overkill for this task.
> 
> @netrome

Oh I missed that there was a parent issue for more context.

**Comment by igorsyl** [comment] 2023-02-17 17:22
Tracked by:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1248500/219721646-c22a255e-172d-469c-a82a-6794ab3a9d79.png">

**Comment by netrome** [comment] 2023-02-17 17:25
> Tracked by:
> 
> <img alt="image" width="266" src="https://user-images.githubusercontent.com/1248500/219721646-c22a255e-172d-469c-a82a-6794ab3a9d79.png">

Yeah I noticed it when you mentioned "parent issue" :sweat_smile:

**Comment by igorsyl** [comment] 2023-02-23 19:09
@donpdonp Can you attach the PR's for the following to this issue? Thx!

- Run frost dkg using in-process frost library "frost-lib" (no network protocol)
- Peg-in: spend a P2PKH utxo and lock it into P2TR output script using the frost public aggregate key.

**Comment by donpdonp** [comment] 2023-03-07 22:19
Title and To-Do reworked to reflect scope of attached PR #75

**Comment by donpdonp** [comment] 2023-03-08 00:24
rust-bitcoin crate example/utility functions

https://github.com/p2pderivatives/rust-dlc/blob/master/dlc/src/util.rs

**Comment by igorsyl** [comment] 2023-03-08 00:26
> rust-bitcoin crate example/utility functions
> 
> https://github.com/p2pderivatives/rust-dlc/blob/master/dlc/src/util.rs

Great find!
Have you tried a GPT prompt as well?

**Comment by donpdonp** [comment] 2023-03-14 20:31
The attached PR is a (failing) integration test. While there is some useful code in the PR, its now a dupe of #52 so I'm closing it.

**Closed by donpdonp** 2023-03-14 20:31 UTC
